initial commit
NotUrBruddah/go-rest-api-homework pull request #1
Opened 2024-07-02 22:54 UTC by NotUrBruddah

2024-07-03 08:27 UTC, dirtymew requested changes
Привет Андрей

хорошая работа - API верно описан

по реализации есть что поправить

2024-07-03 08:27 UTC, dirtymew commented on precode.go
> +	w.Write(resp)
_ , _ = w.Write(resp)

тут нужно либо явно проигнорировать ошибку или ее логировать

2024-07-03 08:27 UTC, dirtymew commented on precode.go
> +	_, err := buf.ReadFrom(r.Body)
не ошибка - но на будущее посмотри на https://pkg.go.dev/encoding/json#NewDecoder

2024-07-03 08:27 UTC, dirtymew commented on precode.go
> +	tasks[task.ID] = task
Код не только добавляет но и обновляет задачу - обычно создание и обновление - это разные энпоинты.

Вообще в задание явно не описано, но судя по коду ответа 201   - должно быть только создание элемента

Eще хорошо бы валидировать то что приходит из вне,  можно значения полей например:
 - если нет id то генерировать - или ошибку возвращать
 -  если нет applications то добавить из запроса user agent https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

2024-07-03 08:27 UTC, dirtymew commented on precode.go
> +func getTaskById(w http.ResponseWriter, r *http.Request) {
лучше назвать просто getTask

2024-07-03 08:27 UTC, dirtymew commented on precode.go
> +		http.Error(w, fmt.Sprintf("No task found with id = [%s]. Nothing to show.", id), http.StatusNoContent)
неверный код ответа при ошибке

2024-07-03 08:27 UTC, dirtymew commented on precode.go
> +		http.Error(w, fmt.Sprintf("No task found with id = [%s]. Nothing to delete.", id), http.StatusNoContent)
неверный код ответа при ошибке

2024-07-03 08:27 UTC, dirtymew commented on precode.go
> +func deleteTaskById(w http.ResponseWriter, r *http.Request) {
лучше просто deleteTask

2024-07-03 08:27 UTC, dirtymew commented on precode.go
> +func postTasks(w http.ResponseWriter, r *http.Request) {
лучше назвать addTask

2024-07-07 16:03 UTC, NotUrBruddah commented on precode.go
> +func postTasks(w http.ResponseWriter, r *http.Request) {
исправлено

2024-07-07 16:03 UTC, NotUrBruddah commented on precode.go
> +func deleteTaskById(w http.ResponseWriter, r *http.Request) {
исправлено

2024-07-07 16:04 UTC, NotUrBruddah commented on precode.go
> +func getTaskById(w http.ResponseWriter, r *http.Request) {
исправлено

2024-07-07 21:22 UTC, NotUrBruddah commented on precode.go
> +	tasks[task.ID] = task
`Код не только добавляет но и обновляет задачу - обычно создание и обновление - это разные энпоинты.

Вообще в задание явно не описано, но судя по коду ответа 201 - должно быть только создание элемента`

Исправлено

2024-07-07 21:24 UTC, NotUrBruddah commented on precode.go
> +	tasks[task.ID] = task
если нет id то генерировать - или ошибку возвращать

добавлена генерация через github.com/gofrs/uuid/v5

2024-07-07 21:37 UTC, NotUrBruddah commented on precode.go
> +	tasks[task.ID] = task
если нет applications то добавить из запроса user agent https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

- добавлено через метод UserAgent()
который обертка над r.Header.Get("User-Agent")

2024-07-07 21:56 UTC, NotUrBruddah commented on precode.go
> +	_, err := buf.ReadFrom(r.Body)
поменял  чтение данных из тела запроса

2024-07-07 21:59 UTC, NotUrBruddah commented on precode.go
> +		http.Error(w, fmt.Sprintf("No task found with id = [%s]. Nothing to delete.", id), http.StatusNoContent)
В случае ошибки или отсутствия задачи в мапе сервер должен вернуть статус 400 Bad Request.

исправлено

2024-07-07 22:01 UTC, NotUrBruddah commented on precode.go
> +		http.Error(w, fmt.Sprintf("No task found with id = [%s]. Nothing to show.", id), http.StatusNoContent)
В случае ошибки или отсутствия задачи в мапе сервер должен вернуть статус 400 Bad Request.

2024-07-07 22:01 UTC, NotUrBruddah commented on precode.go
> +		http.Error(w, fmt.Sprintf("No task found with id = [%s]. Nothing to show.", id), http.StatusNoContent)
Исправлено

2024-07-07 22:27 UTC, NotUrBruddah commented on precode.go
> +	w.Write(resp)
Исправил, но не до конца понял почему нельзя использовать просто 
w.Write(resp) если я игнорирую ошибку ?

2024-07-07 22:56 UTC, dirtymew reviewed
Привет Андрей 

все супер - зачет

2024-07-07 22:56 UTC, dirtymew commented on go.mod
go-rest-api-homework бинарник не стоит коммитеть в репозиторий

2024-07-07 22:56 UTC, dirtymew approved these changes

2024-07-07 23:09 UTC, NotUrBruddah commented on go.mod
понял, забыл .gitignore сделать
сейчас поправлю

2024-07-07 23:23 UTC, merged

2024-07-07 23:32 UTC, dirtymew commented on precode.go
> +	w.Write(resp)
литеры будут ругаться)